-- OAuth Client（接入方应用）
CREATE TABLE IF NOT EXISTS oauth_clients (
    id                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id                   CHAR(26)        NOT NULL,
    client_id                   VARCHAR(64)     NOT NULL,
    client_secret_hash          VARCHAR(255)    NOT NULL,
    name                        VARCHAR(200)    NOT NULL,
    description                 VARCHAR(500)    NULL,
    client_type                 VARCHAR(32)     NOT NULL,
    redirect_uris               JSON            NOT NULL,
    grant_types                 JSON            NOT NULL,
    allowed_scopes              JSON            NOT NULL,
    allowed_tenant_types        JSON            NOT NULL,
    require_pkce                BOOLEAN         NOT NULL DEFAULT TRUE,
    access_token_ttl_seconds    INT UNSIGNED    NOT NULL DEFAULT 7200,
    refresh_token_ttl_seconds   INT UNSIGNED    NOT NULL DEFAULT 2592000,
    allowed_ip_cidrs            JSON            NULL,
    status                      VARCHAR(20)     NOT NULL DEFAULT 'active',
    created_at                  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at                  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    created_by                  BIGINT UNSIGNED NULL,
    updated_by                  BIGINT UNSIGNED NULL,
    deleted                     BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    UNIQUE KEY uk_public_id (public_id),
    UNIQUE KEY uk_client_id (client_id),
    KEY idx_status  (status, deleted),
    KEY idx_type    (client_type),
    KEY idx_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='OAuth Client（接入方应用）';
